### ISSUE TITLE
Radzen.Blazor.RadzenDropDown.SelectAll() System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ADefWebserver** [mytatuo/GTAVehicles#10]
Upgrade to the latest Radzen.
On the dropdown, when you select "Select All" you get this error:

[2019-10-09T20:20:10.347Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Radzen.Blazor.RadzenDropDown.SelectAll()
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)

**Comment by ADefWebserver** [comment]
Fixed with https://github.com/mytatuo/GTAVehicles/commit/92107b999b3a2fd9803cd2f67680fff3223b3663#diff-f8b1201be3fc1c5f75272ca2cd2d2d45
